TEST_SAMPLE=05483-13-appt1000_hg38_ASv2
INPUT_SUP_BAM=/faststorage/project/nanopore_kga/STORAGE/260602v3_Nanopore_Adaptiv/05483-13/05483-13sup_AS.bam
ANALYSIS_DIR=/faststorage/project/nanopore_kga/workflow_dev/apptainer_test/fullpipe_analysis
SUBSET_READS=1000
REF_GENOME=hg38
REF_FILE=hg38_noAlt.fasta
AS_VERSION=v2
