REFERENCE_DIR=/faststorage/project/nanopore_kga/STORAGE/resources/references
DATA_DIR=/faststorage/project/nanopore_kga/STORAGE/resources/data
SOFTWARE_DIR=/faststorage/project/nanopore_kga/STORAGE/resources/software

HG38_REF=hg38_noAlt.fasta
T2T_REF=GCF_009914755.1_T2T-CHM13v2.0_genomic.fna
CLAIR3_MODEL=r1041_e82_400bps_sup_v520

ANALYSIS_DIR=/faststorage/project/nanopore_kga/analysis_v2
DORADO_BIN=/faststorage/project/nanopore_kga/tools/dorado-2.1.1-linux-x64/bin/dorado
AS_BED_DIR=/faststorage/project/nanopore_kga/development/adaptiveSamplingBed
VARSEQ_HOST=varseq-02
VARSEQ_SUBMIT_HOST=fe-open-01
VARSEQ_REMOTE_SCRIPT=/faststorage/project/nanopore_kga/workflow_dev/scripts/varseq_remote_runner.sh
